# Generated by Django 2.1 on 2018-08-27 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dostuff', '0008_auto_20180821_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='latitude',
            field=models.FloatField(default=41.881832),
        ),
        migrations.AddField(
            model_name='event',
            name='longitude',
            field=models.FloatField(default=-87.623177),
        ),
    ]
