# Generated by Django 2.1 on 2018-08-28 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dostuff', '0009_auto_20180827_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
